# automatically generated by the FlatBuffers compiler, do not modify
# namespace: SmartCameraV2
import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class CountData:
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CountData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCountData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # CountData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CountData
    def ClassId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags, o + self._tab.Pos
            )
        return 0

    # CountData
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint32Flags, o + self._tab.Pos
            )
        return 0


def CountDataStart(builder):
    builder.StartObject(2)


def Start(builder):
    return CountDataStart(builder)


def CountDataAddClassId(builder, classId):
    builder.PrependUint32Slot(0, classId, 0)


def AddClassId(builder, classId):
    return CountDataAddClassId(builder, classId)


def CountDataAddCount(builder, count):
    builder.PrependUint32Slot(1, count, 0)


def AddCount(builder, count):
    return CountDataAddCount(builder, count)


def CountDataEnd(builder):
    return builder.EndObject()


def End(builder):
    return CountDataEnd(builder)
