FROM node:20-slim AS base

ENV NPM_HOME="/npm"
ENV PATH="$NPM_HOME:$PATH"

FROM base AS prod

WORKDIR /app
COPY ./app/package.json /app
COPY ./app/package-lock.json /app
RUN npm ci
RUN npm i -g http-server

COPY ./app /app

EXPOSE 3000
CMD npm run build && http-server -p 3000 /app/dist
