exclude: '(\.vscode/.*\.json|backend/client_specs/)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-added-large-files
      - id: debug-statements
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln
        args: [--all]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
        args: [--py39-plus]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  - repo: https://github.com/whtsky/pre-commit-pretty-format-json5
    rev: "1.0.0"
    hooks:
       - id: pretty-format-json5
         args: [--autofix, --no-sort-keys]

