services:
  db:
    image: postgres:17.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEBUG_DEPENDENCIES: "true"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      DEBUGGER: ${DEBUGGER}
    ports:
      - "8000:8000"
      - "10001:10001"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    command: uvicorn app.main:app --host "0.0.0.0" --port 8000 --reload

volumes:
  pgdata:
